export type {
  CanonicalNodeSummary,
  ClientLogger,
  NodeListResult,
  MutationPolicy,
  ReconnectPolicy,
  ServerInfoResult,
  TimeoutPolicy,
  VersionPolicy,
  ZwjsCommandRequest,
  ZwjsCommandResult,
  ZwjsProtocolErrorPayload,
  ZwjsAuthConfig,
  ZwjsClient,
  ZwjsClientConfig,
  ZwjsControllerStateResult,
  ZwjsControllerNodeNeighborsResult,
  ZwjsClientEvent,
  ZwjsControllerNvmConvertProgressEventPayload,
  ZwjsControllerNvmBackupProgressEventPayload,
  ZwjsControllerGrantSecurityClassesEventPayload,
  ZwjsControllerInclusionAbortedEventPayload,
  ZwjsControllerNvmRestoreProgressEventPayload,
  ZwjsControllerValidateDskAndEnterPinEventPayload,
  ZwjsDriverLoggingEventPayload,
  ZwjsNodeMetadataUpdatedEventPayload,
  ZwjsNodeNotificationEventPayload,
  ZwjsNodeInterviewCompletedEventPayload,
  ZwjsNodeInterviewFailedEventPayload,
  ZwjsNodeInterviewStageCompletedEventPayload,
  ZwjsNodeInterviewStartedEventPayload,
  ZwjsNodeSleepEventPayload,
  ZwjsNodeValueNotificationEventPayload,
  ZwjsNodeValueAddedEventPayload,
  ZwjsNodeCheckLifelineHealthProgressEventPayload,
  ZwjsNodeCheckRouteHealthProgressEventPayload,
  ZwjsNodeValueRemovedEventPayload,
  ZwjsNodeTestPowerlevelProgressEventPayload,
  ZwjsNodeValueUpdatedEventPayload,
  ZwjsNodeWakeUpEventPayload,
  ZwjsInitializeOptions,
  ZwjsLogFilter,
  ZwjsControllerBeginInclusionArgs,
  ZwjsControllerBeginExclusionArgs,
  ZwjsControllerInclusionCommandResult,
  ZwjsDriverConfig,
  ZwjsDriverLogConfigResult,
  ZwjsDriverStatisticsEnabledResult,
  ZwjsDefinedValueIdsResult,
  ZwjsDefinedValueId,
  ZwjsNodeStateResult,
  ZwjsNodeValueMetadataResult,
  ZwjsNodeValueEnvelopeResult,
  ZwjsNodeValueResult,
  ZwjsNodeSupportedNotificationEventsResult,
  ZwjsNodeFirmwareUpdateCapabilitiesResult,
  ZwjsNodeFirmwareUpdateCapabilitiesCachedResult,
  ZwjsNodeDateAndTimeResult,
  ZwjsNodeFirmwareUpdateInProgressResult,
  ZwjsNodeFirmwareUpdateProgressResult,
  ZwjsNodeHealthCheckInProgressResult,
  ZwjsNodeDeviceConfigChangedResult,
  ZwjsNodePingResult,
  ZwjsNodeRefreshInfoResult,
  ZwjsNodeRefreshValuesResult,
  ZwjsNodePollValueArgs,
  ZwjsNodePollValueResult,
  ZwjsEndpointTarget,
  ZwjsEndpointCcQuery,
  ZwjsEndpointInvokeCcApiArgs,
  ZwjsEndpointSupportsCcResult,
  ZwjsEndpointSupportsCcApiResult,
  ZwjsEndpointControlsCcResult,
  ZwjsEndpointIsCcSecureResult,
  ZwjsEndpointGetCcVersionResult,
  ZwjsEndpointNodeRefResult,
  ZwjsMulticastGroupTarget,
  ZwjsVirtualEndpointCcQuery,
  ZwjsVirtualEndpointInvokeCcApiArgs,
  ZwjsVirtualEndpointEndpointCountResult,
  ZwjsVirtualEndpointSupportsCcResult,
  ZwjsVirtualEndpointSupportsCcApiResult,
  ZwjsVirtualEndpointGetCcVersionResult,
  ZwjsVirtualEndpointDefinedValueIdsResult,
  ZwjsInvokeCcApiResult,
  ZwjsNodeValueTimestampResult,
  ZwjsClientStatus,
  ZwjsValueId,
} from './client/types';
export type { MutationPolicyPresetName } from './client/mutation-policy-presets';
export type { ClientErrorSummary, ZwjsClientErrorCode } from './errors';
export type {
  ZwjsEventFrame,
  ZwjsProtocolCommandFrame,
  ZwjsResultErrorFrame,
  ZwjsResultFrame,
  ZwjsResultSuccessFrame,
  ZwjsVersionFrame,
} from './protocol/raw-frame-types';
export {
  extractZwjsDefinedValueIds,
  isZwjsDefinedValueId,
  isZwjsValueId,
} from './protocol/value-id-guards';
export {
  extractZwjsNodeValue,
  hasZwjsNodeValue,
  isZwjsNodeValueEnvelopeResult,
} from './protocol/value-result-guards';
export {
  createMutationPolicyPreset,
  getMutationPolicyPresetAllowlist,
} from './client/mutation-policy-presets';

import { ZwjsClientImpl } from './client/zwjs-client';
import type { ZwjsClient, ZwjsClientConfig } from './client/types';

export function createZwjsClient(config: ZwjsClientConfig): ZwjsClient {
  return new ZwjsClientImpl(config);
}
